import Icon from "../components/iconify/iconify";
import { AppConstants } from "../utils/appConstants";
export const routeConfig = [
  {
    title: AppConstants.sidebarConstants.dashboard,
    link: "dashboard",
    path: "/app",
    icon: <Icon icon="ri:dashboard-fill" />,
    role: ["superAdmin","reviewerAdmin","legalAdmin","financeAdmin"],
    show: true,
  },
  {
    title: AppConstants.sidebarConstants.manageUsers,
    link: "manage-users",
    icon: <Icon icon="mdi:users" />,
    path: "/src/pages/manageUsers/index",
    role: ["superAdmin" , 'reviewerAdmin'],
    show: true,
  },
  {
    title: "Add User",
    link: "manage-users/add-user",
    path: "/src/pages/manageUsers/add-user.jsx",
    show: false,
  },
  {
    title: "Add Employee",
    link: "manage-employees/add-employees",
    path: "/src/pages/manage-employees/add-employee.jsx",
    show: false,
  },
  {
    title: "User details",
    link: "manage-users/user-details",
    path: "/src/pages/manageUsers/user-details",
    show: false,
  },
  {
    title: AppConstants.sidebarConstants.manageEmployees,
    link: "manage-employees",
    path: "/src/pages/manage-employees",
    icon: <Icon icon="clarity:employee-group-solid" />,
    role: ["superAdmin"],
    show: true,
  },
  {
    title: AppConstants.sidebarConstants.rolesAndPremission,
    link: "roles-and-permissions-management",
    path: "./pages/rolePermissions",
    icon: <Icon icon="fluent-mdl2:permissions" />,
    role: ["superAdmin"],
    show: true,
  },

  {
    title: AppConstants.sidebarConstants.propertyManagement,
    link: "property-management",
    path: "./pages/propertyManagement",
    icon: <Icon icon="ph:warehouse-thin" />,
    role: ["superAdmin", 'reviewerAdmin',"legalAdmin"],
    show: true,
  },
  {
    title: AppConstants.sidebarConstants.reviewRating,
    link: "review-and-rating-mgt",
    path: "./pages/reviewRating",
    icon: <Icon icon="carbon:review" />,
    role: ["superAdmin", 'reviewerAdmin'],
    show: true,
  },
  {
    title: AppConstants.sidebarConstants.financialPerformance,
    link: "finance-performance",
    path: "./pages/financialPerformance",
    icon: <Icon icon="material-symbols:finance" />,
    role: ["superAdmin","financeAdmin"],
    show: true,
  },
  {
    title: AppConstants.sidebarConstants.manageTransactions,
    link: "manage-transactions",
    path: "./pages/manageTransactions",
    icon: <Icon icon="ant-design:transaction-outlined" />,
    role: ["superAdmin","financeAdmin"],
    show: true,
  },
  {
    title: AppConstants.sidebarConstants.managePayouts,
    link: "manage-payouts",
    path: "./pages/managePayouts",
    role: ["superAdmin"],
    icon: <Icon icon="heroicons:currency-rupee" />,
    show: true,
  },
  {
    title: AppConstants.sidebarConstants.activityLog,
    link: "activity-logs",
    path: "./pages/activityLog",
    icon: <Icon icon="tdesign:activity" />,
    role: ["superAdmin"],
    show: true,
  },
  {
    title: AppConstants.sidebarConstants.manageChat,
    link: "manage-chat",
    path: "./pages/manageChat",
    role: ["superAdmin"],
    icon: <Icon icon="majesticons:chat-line" />,
    show: true,
  },
  {
    title: "Manage Blogs",
    link: "manage-blogs",
    path: "./pages/manage-blogs",
    role: ["superAdmin"],
    icon: <Icon icon="mdi:blog" />,
    show: true,
  },
  {
    title: "Manage AboutUs",
    link: "manage-aboutUs",
    path: "./pages/manage-aboutUs",
    role: ["superAdmin"],
    icon: <Icon icon="mdi:about-circle-outline" />,
    show: true,
  },
  {
    title: "Manage Careers",
    link: "manage-careers",
    path: "./pages/manage-careers",
    role: ["superAdmin"],
    icon: <Icon icon="marketeq:job" />,
    show: true,
  },
  {
    title: "Create Testimonials",
    link: "create-testimonials",
    path: "./pages/create-testimonials/add-testimonials",
    role: ["superAdmin"],
    icon: <Icon icon="fluent:chat-sparkle-16-regular" />,
    show: false,
  },
  {
    title: "Manage Testimonials",
    link: "testimonials",
    path: "./pages/create-testimonials",
    role: ["superAdmin"],
    icon: <Icon icon="fluent:chat-sparkle-16-regular" />,
    show: true,
  },
  {
    title: "Manage Privacy Policy",
    link: "manage-privacy-policy",
    path: "./pages/manage-privacy-policy",
    role: ["superAdmin"],
    icon: <Icon icon="ic:baseline-privacy-tip" />,
    show: true,
  },
  {
    title: "Manage FAQ's",
    link: "manage-faq",
    path: "./pages/manage-faq",
    role: ["superAdmin"],
    icon: <Icon icon="mdi:faq" />,
    show: true,
  },
];
